// This file is automatically generated.
// Please do not change this file!
interface CssExports {
  debugResponseTimeIndicator: string;
}
declare const cssExports: CssExports;
export default cssExports;
