// This file is automatically generated.
// Please do not change this file!
interface CssExports {
  'app-status-title-context-info': string;
  appStatusTitleContextInfo: string;
  description: string;
  'last-status': string;
  lastStatus: string;
}
declare const cssExports: CssExports;
export default cssExports;
