// This file is automatically generated.
// Please do not change this file!
interface CssExports {
  actions: string;
  blink: string;
  bookContainer: string;
  bookImages: string;
  bookWrapper: string;
  controlNext: string;
  controlPrev: string;
  hidden: string;
  inside: string;
  insideAnimation: string;
  insideAnimationReverse: string;
  insideHalfIcon: string;
  insideIcon: string;
  messageFormattedString: string;
  outSide: string;
  page: string;
  pageAnimation: string;
  pageAnimationReverse: string;
  pageButtonAnimationReverse: string;
  pageSecondTextAnimation: string;
  pageSecondTextAnimationReverse: string;
  pageTextAnimation: string;
  pageTextAnimationReverse: string;
  text: string;
  textArea: string;
  titleAnimation: string;
  titleAnimationReverse: string;
  titleContent: string;
  titleContentAnimation: string;
  titleContentAnimationReverse: string;
  titleIcon: string;
  uneditable: string;
}
declare const cssExports: CssExports;
export default cssExports;
