// This file is automatically generated.
// Please do not change this file!
interface CssExports {
  button: string;
  icon: string;
}
declare const cssExports: CssExports;
export default cssExports;
