// This file is automatically generated.
// Please do not change this file!
interface CssExports {
  worldLayersContainer: string;
  world_layers_container: string;
}
declare const cssExports: CssExports;
export default cssExports;
