// This file is automatically generated.
// Please do not change this file!
interface CssExports {
  closeButton: string;
  closeIcon: string;
  container: string;
  contentWrapper: string;
  link: string;
  list: string;
  listItem: string;
  modalScreen: string;
  paragraph: string;
  sectionTitle: string;
  subtitle: string;
  title: string;
}
declare const cssExports: CssExports;
export default cssExports;
