// This file is automatically generated.
// Please do not change this file!
interface CssExports {
  'debug-left-side': string;
  'debug-right-side': string;
  debugLeftSide: string;
  debugRightSide: string;
  empty: string;
}
declare const cssExports: CssExports;
export default cssExports;
