// This file is automatically generated.
// Please do not change this file!
interface CssExports {
  actionBinds: string;
  actionName: string;
  button: string;
  'chat-command': string;
  chatCommand: string;
  container: string;
  group: string;
  'group-category': string;
  groupCategory: string;
  'margin-left': string;
  marginLeft: string;
  'matched-bind': string;
  'matched-bind-warning': string;
  matchedBind: string;
  matchedBindWarning: string;
  'undo-gamepad': string;
  'undo-keyboard': string;
  undoGamepad: string;
  undoKeyboard: string;
  'warning-container': string;
  warningContainer: string;
}
declare const cssExports: CssExports;
export default cssExports;
