// This file is automatically generated.
// Please do not change this file!
interface CssExports {
  'chat-btn': string;
  chatBtn: string;
  'debug-btn': string;
  debugBtn: string;
  'mobile-top-btns': string;
  mobileTopBtns: string;
  'pause-btn': string;
  pauseBtn: string;
  'tab-btn': string;
  tabBtn: string;
}
declare const cssExports: CssExports;
export default cssExports;
