// This file is automatically generated.
// Please do not change this file!
interface CssExports {
  arrowRow: string;
  container: string;
  dataRow: string;
  iconRow: string;
  ping: string;
  stale: string;
  totalRow: string;
  websocket: string;
}
declare const cssExports: CssExports;
export default cssExports;
