// This file is automatically generated.
// Please do not change this file!
interface CssExports {
  pauseContainer: string;
  pause_container: string;
  row: string;
  title: string;
}
declare const cssExports: CssExports;
export default cssExports;
