// This file is automatically generated.
// Please do not change this file!
interface CssExports {
  column: string;
  container: string;
  sliderGroup: string;
}
declare const cssExports: CssExports;
export default cssExports;
