// This file is automatically generated.
// Please do not change this file!
interface CssExports {
  content: string;
  contentLoading: string;
  content_loading: string;
  imageMissing: string;
  image_missing: string;
  root: string;
  title: string;
  worldFocused: string;
  worldImage: string;
  worldInfo: string;
  worldInfoDescriptionLine: string;
  worldInfoFormatted: string;
  worldRoot: string;
  worldTitle: string;
  worldTitleRight: string;
  world_focused: string;
  world_image: string;
  world_info: string;
  world_info_description_line: string;
  world_info_formatted: string;
  world_root: string;
  world_title: string;
  world_title_right: string;
}
declare const cssExports: CssExports;
export default cssExports;
