// This file is automatically generated.
// Please do not change this file!
interface CssExports {
  disabled: string;
  label: string;
  slider: string;
  'slider-container': string;
  'slider-thumb': string;
  sliderContainer: string;
  sliderThumb: string;
}
declare const cssExports: CssExports;
export default cssExports;
