// This file is automatically generated.
// Please do not change this file!
interface CssExports {
  hintContainer: string;
  hintText: string;
  hint_container: string;
  hint_text: string;
}
declare const cssExports: CssExports;
export default cssExports;
