// This file is automatically generated.
// Please do not change this file!
interface CssExports {
  'xp-bar': string;
  'xp-bar-bg': string;
  'xp-label': string;
  xpBar: string;
  xpBarBg: string;
  xpLabel: string;
}
declare const cssExports: CssExports;
export default cssExports;
